comment:
  image:
    repository: torchun/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: torchun/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: torchun/ui
    tag: latest
  service:
    externalPort: 9292
