global:
  slack_api_url: 'https://hooks.slack.com/services/<get_webhook_url_from_slack>'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#my_channel_name'
