version: "3.3"
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend

  ui:
    image: ${USER_NAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend

  post:
    image: ${USER_NAME}/post:${POST_TAG}
    environment:
      - POST_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend

  comment:
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    environment:
      - COMMENT_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=1d"
    networks:
      - frontend
      - backend

  node-exporter:
#    image: prom/node-exporter:v0.15.2
    image: prom/node-exporter:v1.1.1
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - frontend
      - backend

volumes:
  post_db:
  prometheus_data:

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  backend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
