version: "3.3"
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend

  ui:
    image: ${USER_NAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_TAG}
    environment:
      - POST_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    environment:
      - COMMENT_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend

#  prometheus:
#    image: ${USER_NAME}/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - prometheus_data:/prometheus
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#      - "--storage.tsdb.path=/prometheus"
#      - "--storage.tsdb.retention=1d"
#    networks:
#      - frontend
#      - backend

#  node-exporter:
#    image: prom/node-exporter:v1.1.1
#    user: root
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
#    networks:
#      - frontend
#      - backend

#  mongo-exporter:
#    image: ${USER_NAME}/mongodb_exporter:0.20.2
#    command:
#      - '--mongodb.uri=mongodb://mongo_db:27017'
#    networks:
#      - backend

#  blackbox-exporter:
#    image: ${USER_NAME}/blackbox_exporter
#    command:
#      - '--config.file=/etc/blackboxexporter/config.yml'
#    networks:
#      - backend
#      - frontend

volumes:
  post_db:
#  prometheus_data:

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  backend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
