---
- name: Install
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Wait server
      wait_for_connection:
    - name: Gather facts for first time
      setup:

- import_playbook: k8s-environment.yml
- import_playbook: k8s-master.yml
- import_playbook: k8s-worker.yml
